# Generated by Django 4.1.4 on 2022-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='picture',
            field=models.ImageField(blank=True, upload_to='workers/%Y/%m/%d', verbose_name='Worker picture'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='facebook_profil',
            field=models.CharField(max_length=100, verbose_name='Account of Facebook'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='job',
            field=models.CharField(max_length=50, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='youtube_profil',
            field=models.CharField(max_length=100, verbose_name='Account of Instagram'),
        ),
    ]
